### ISSUE TITLE
Using Library In swift

### ISSUE THREAD

**Issue by omernave** [renebigot/XlsxReaderWriter#3]
I posted this problem on Stackoverflow - http://stackoverflow.com/questions/32334566/setting-up-xlsxreaderwriter-swift

I'm trying to use this library in swift, I've followed the steps and added a bridging-header with this import statement - #import "BRAOfficeDocumentPackage.h".

I can't get the library to work, can you help?

**Comment by renebigot** [comment]
I've just committed a Swift header bridge. Let me know if you got any other problem.

**Comment by omernave** [comment]
I've added the project as a sub-project and added it in the target dependencies, I also added the libXlsxReaderWriter library in the link binary.

then I added a bridging header, the same as you added but I still can't access the library.
But now I don't get an error saying the file i'm trying to import doesn't exist and project compiles.

**Comment by renebigot** [comment]
OK, same bug here... I'll try to do something. I'm new to Swift so I need some time to debug this.

**Comment by omernave** [comment]
Have you managed to fix the problem?

**Comment by renebigot** [comment]
Hello omernave. I've successfully included the lib in a fresh new Swift project. You should follow the new README.MD instruction for "Linking (Objective-C" and "Linking (Swift Bridging)". You could find a simple Read/Write code in the examples or in the new Swift test case class.

**Comment by omernave** [comment]
Can you upload a sample swift project that uses the library? I can't get it to work.

**Comment by omernave** [comment]
Thanks a lot, I got it working!

**Comment by omernave** [comment]
The library is linked to my project but when I try to read a sample xlsx I get errors:
![screen shot 2015-09-08 at 21 49 43](https://cloud.githubusercontent.com/assets/12939362/9744290/ab27e640-5673-11e5-961c-5f795ab3ff2e.png)

**Comment by renebigot** [comment]
Yes. I've forgotten to write this in README.MD. You have to add -lz in other linker flag or to add libz as project dependencies. Sorry.

**Comment by Harshrajput** [comment]
I am using this lib but could not import in swift 4. So please help me . If it is fine for swift 4 . As well as I can download in proper way.
